-- Initializing remaining Service Info for Legal & Forensic Services
INSERT INTO celibacyinfo (service_name, description, requirements, processing_time, price, currency, provided_by) VALUES ('Certificate of Being Single (Celibacy)', 'Official proof of marital status for legal unions.', '1. Local Gov Recommendation\n2. National ID Copy', '2 Days', 1200, 'RWF', 'MINALOC');
INSERT INTO contractinfo (service_name, description, requirements, processing_time, price, currency, provided_by) VALUES ('Employment Contract Certification', 'Legal verification of employment terms and conditions.', '1. Signed Contract Copy\n2. Employer Registration', '5 Days', 3000, 'RWF', 'MIFOTRA');
INSERT INTO courtjudgmentinfo (service_name, description, requirements, processing_time, price, currency, provided_by) VALUES ('Copy of Court Judgment', 'Official certified copy of a court ruling (Gacaca or Primary).', '1. Case Number\n2. Year of Ruling', '7 Days', 5000, 'RWF', 'MINIJUST');
INSERT INTO criminalrecordinfo_serv (service_name, description, requirements, processing_time, price, currency, provided_by) VALUES ('Criminal Record Clearance', 'Verification of clear criminal background for employment or travel.', '1. NIDA ID Scan\n2. Purpose of Request', '3 Days', 1200, 'RWF', 'NPPA');
INSERT INTO notarialactinfo (service_name, description, requirements, processing_time, price, currency, provided_by) VALUES ('Notarial Act Authentication', 'Legal certification of documents and signatures by a public notary.', '1. Original Document\n2. Identification', '1 Day', 10000, 'RWF', 'MINIJUST');
INSERT INTO poainfo (service_name, description, requirements, processing_time, price, currency, provided_by) VALUES ('Power of Attorney Certification', 'Legal authorization granted to a third party to represent a citizen.', '1. Signed POA Draft\n2. Appointee ID', '2 Days', 5000, 'RWF', 'MINIJUST');

-- Creating remaining Application Tables
CREATE TABLE IF NOT EXISTS applicationcelibacy (id INT AUTO_INCREMENT PRIMARY KEY, full_name VARCHAR(255), national_id VARCHAR(20), birth_district VARCHAR(100), document_path VARCHAR(512), service_name VARCHAR(255), status ENUM('Pending', 'Approved', 'Rejected') DEFAULT 'Pending', ai_forgery_score FLOAT, ai_verdict VARCHAR(50), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS applicationcontract (id INT AUTO_INCREMENT PRIMARY KEY, full_name VARCHAR(255), national_id VARCHAR(20), employer_id VARCHAR(50), job_title VARCHAR(100), document_path VARCHAR(512), service_name VARCHAR(255), status ENUM('Pending', 'Approved', 'Rejected') DEFAULT 'Pending', ai_forgery_score FLOAT, ai_verdict VARCHAR(50), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS applicationcourtjudgment (id INT AUTO_INCREMENT PRIMARY KEY, full_name VARCHAR(255), national_id VARCHAR(20), case_number VARCHAR(100), ruling_year INT, document_path VARCHAR(512), service_name VARCHAR(255), status ENUM('Pending', 'Approved', 'Rejected') DEFAULT 'Pending', ai_forgery_score FLOAT, ai_verdict VARCHAR(50), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS applicationnotarialact (id INT AUTO_INCREMENT PRIMARY KEY, full_name VARCHAR(255), national_id VARCHAR(20), act_type VARCHAR(100), document_path VARCHAR(512), service_name VARCHAR(255), status ENUM('Pending', 'Approved', 'Rejected') DEFAULT 'Pending', ai_forgery_score FLOAT, ai_verdict VARCHAR(50), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS applicationpoa (id INT AUTO_INCREMENT PRIMARY KEY, full_name VARCHAR(255), national_id VARCHAR(20), appointee_name VARCHAR(255), appointee_id VARCHAR(20), document_path VARCHAR(512), service_name VARCHAR(255), status ENUM('Pending', 'Approved', 'Rejected') DEFAULT 'Pending', ai_forgery_score FLOAT, ai_verdict VARCHAR(50), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
