-- Service Info Tables (Settings)
CREATE TABLE salaryslipinfo (id INT AUTO_INCREMENT PRIMARY KEY, service_name VARCHAR(255), description TEXT, requirements TEXT, processing_time VARCHAR(100), price INT, currency VARCHAR(10), provided_by VARCHAR(255), status ENUM('Active', 'Inactive') DEFAULT 'Active');
CREATE TABLE bankstatementinfo (id INT AUTO_INCREMENT PRIMARY KEY, service_name VARCHAR(255), description TEXT, requirements TEXT, processing_time VARCHAR(100), price INT, currency VARCHAR(10), provided_by VARCHAR(255), status ENUM('Active', 'Inactive') DEFAULT 'Active');
CREATE TABLE academictranscriptinfo (id INT AUTO_INCREMENT PRIMARY KEY, service_name VARCHAR(255), description TEXT, requirements TEXT, processing_time VARCHAR(100), price INT, currency VARCHAR(10), provided_by VARCHAR(255), status ENUM('Active', 'Inactive') DEFAULT 'Active');
CREATE TABLE criminalrecordinfo_serv (id INT AUTO_INCREMENT PRIMARY KEY, service_name VARCHAR(255), description TEXT, requirements TEXT, processing_time VARCHAR(100), price INT, currency VARCHAR(10), provided_by VARCHAR(255), status ENUM('Active', 'Inactive') DEFAULT 'Active');
CREATE TABLE celibacyinfo (id INT AUTO_INCREMENT PRIMARY KEY, service_name VARCHAR(255), description TEXT, requirements TEXT, processing_time VARCHAR(100), price INT, currency VARCHAR(10), provided_by VARCHAR(255), status ENUM('Active', 'Inactive') DEFAULT 'Active');
CREATE TABLE contractinfo (id INT AUTO_INCREMENT PRIMARY KEY, service_name VARCHAR(255), description TEXT, requirements TEXT, processing_time VARCHAR(100), price INT, currency VARCHAR(10), provided_by VARCHAR(255), status ENUM('Active', 'Inactive') DEFAULT 'Active');
CREATE TABLE courtjudgmentinfo (id INT AUTO_INCREMENT PRIMARY KEY, service_name VARCHAR(255), description TEXT, requirements TEXT, processing_time VARCHAR(100), price INT, currency VARCHAR(10), provided_by VARCHAR(255), status ENUM('Active', 'Inactive') DEFAULT 'Active');
CREATE TABLE notarialactinfo (id INT AUTO_INCREMENT PRIMARY KEY, service_name VARCHAR(255), description TEXT, requirements TEXT, processing_time VARCHAR(100), price INT, currency VARCHAR(10), provided_by VARCHAR(255), status ENUM('Active', 'Inactive') DEFAULT 'Active');
CREATE TABLE poainfo (id INT AUTO_INCREMENT PRIMARY KEY, service_name VARCHAR(255), description TEXT, requirements TEXT, processing_time VARCHAR(100), price INT, currency VARCHAR(10), provided_by VARCHAR(255), status ENUM('Active', 'Inactive') DEFAULT 'Active');

-- Seed Initial Content
INSERT INTO salaryslipinfo (service_name, description, requirements, processing_time, price, currency, provided_by) VALUES ('Request for Certified Salary Statement', 'Official verification of lunar/monthly income from employers.', '1. Current Salary Slip\n2. Employment ID', '3 Days', 5000, 'RWF', 'MINALOC');
INSERT INTO bankstatementinfo (service_name, description, requirements, processing_time, price, currency, provided_by) VALUES ('Authentication of Bank Statement', 'Official authentication of bank account transaction history.', '1. Original PDF Statement', '1 Day', 2000, 'RWF', 'BNR');

-- Application Tables
CREATE TABLE applicationsalaryslip (id INT AUTO_INCREMENT PRIMARY KEY, full_name VARCHAR(255), email VARCHAR(255), phone VARCHAR(20), national_id VARCHAR(20), employer_name VARCHAR(255), monthly_net INT, document_path VARCHAR(512), service_name VARCHAR(255), status ENUM('Pending', 'Approved', 'Rejected') DEFAULT 'Pending', ai_forgery_score FLOAT, ai_verdict VARCHAR(50), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE applicationbankstatement (id INT AUTO_INCREMENT PRIMARY KEY, full_name VARCHAR(255), email VARCHAR(255), phone VARCHAR(20), national_id VARCHAR(20), bank_name VARCHAR(255), account_number VARCHAR(50), document_path VARCHAR(512), service_name VARCHAR(255), status ENUM('Pending', 'Approved', 'Rejected') DEFAULT 'Pending', ai_forgery_score FLOAT, ai_verdict VARCHAR(50), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
