<?php
function __($key) {
    if(!isset($_SESSION['lang'])) {
        $_SESSION['lang'] = 'en';
    }
    $lang = $_SESSION['lang'];
    
    $dictionary = [
        'en' => [
            'my_applications' => 'My Applications',
            'documents' => 'Documents',
            'data_history' => 'Data Access History',
            'my_appeals' => 'My Appeals',
            'app_no' => 'App ID',
            'service' => 'Service',
            'status' => 'Status',
            'fee' => 'Fee',
            'date' => 'Date',
            'actions' => 'Actions',
            'appeal' => 'Appeal',
            'pending' => 'Pending',
            'approved' => 'Approved',
            'rejected' => 'Rejected',
            'cancelled' => 'Cancelled',
            'view' => 'View',
            'cancel' => 'Cancel',
            'remind' => 'Remind',
            'login' => 'Login',
            'signup' => 'Sign Up',
            'logout' => 'Log Out',
            'account' => 'Account',
            'english' => 'English',
            'kinyarwanda' => 'Kinyarwanda',
            'french' => 'French',
            'language' => 'Language',
            'applications' => 'Applications',
            'manage_account' => 'Manage My Irembo Account',
            'total_pending' => 'Total Pending',
            'position' => 'Position',
            'before_you' => 'Before You',
            
            // Services
            'replacement_of_national_id_card' => 'Replacement of National ID',
            'replacement_of_driving_license' => 'Replacement of Driving License',
            'replacement_of_passport' => 'Replacement of Passport',
            'marriage_certificate_cert' => 'Marriage Certificate',
            'criminal_record_certificate' => 'Criminal Record Certificate',
            'certificate_of_good_conduct' => 'Certificate of Good Conduct',
            'application_for_provisional_driving_license' => 'Provisional Driving License',
            'application_for_definitive_driving_license' => 'Definitive Driving License',
            'application_for_new_passport' => 'New Passport Application'
        ],
        'rw' => [
            'my_applications' => 'Ibimaze Kuzuzwa',
            'documents' => 'Inyandiko',
            'data_history' => 'Amateka y\'ikoreshwa',
            'my_appeals' => 'Ubujurire bwanjye',
            'app_no' => 'Inomero',
            'service' => 'Serivisi',
            'status' => 'Imiterere',
            'fee' => 'Amafaranga',
            'date' => 'Itariki',
            'actions' => 'Ibikorerwa',
            'appeal' => 'Ajurira',
            'pending' => 'Irangereje',
            'approved' => 'Byemejwe',
            'rejected' => 'Byanze',
            'cancelled' => 'Byahagaritswe',
            'view' => 'Reba',
            'cancel' => 'Hagarika',
            'remind' => 'Kwibutsa',
            'login' => 'Injira',
            'signup' => 'Iyandikishe',
            'logout' => 'Sohoka',
            'account' => 'Konti',
            'english' => 'Icyongereza',
            'kinyarwanda' => 'Kinyarwanda',
            'french' => 'Igifaransa',
            'language' => 'Ururimi',
            'applications' => 'Saba Serivisi',
            'manage_account' => 'Cunga Konti ywanjye ya Irembo',
            'total_pending' => 'Zose ziri gutegerezwa',
            'position' => 'Umwanya',
            'before_you' => 'Abiri mbere yawe',
            
            // Services
            'replacement_of_national_id_card' => 'Gusimbuza Indangamuntu',
            'replacement_of_driving_license' => 'Gusimbuza Permi',
            'replacement_of_passport' => 'Gusimbuza Pasiporo',
            'marriage_certificate_cert' => 'Icyemezo cy\'Ishyingirwa',
            'criminal_record_certificate' => 'Icyemezo cy\'Urukiko',
            'certificate_of_good_conduct' => 'Icyemezo cy\'Imyitwarire Myiza',
            'application_for_provisional_driving_license' => 'Guharanira Permi y\'agateganyo',
            'application_for_definitive_driving_license' => 'Guharanira Permi ya burundu',
            'application_for_new_passport' => 'Gusaba Pasiporo nshya'
        ],
        'fr' => [
            'my_applications' => 'Mes Demandes',
            'documents' => 'Documents',
            'data_history' => 'Historique d\'Accès',
            'my_appeals' => 'Mes Recours',
            'app_no' => 'N° Demande',
            'service' => 'Service',
            'status' => 'Statut',
            'fee' => 'Frais',
            'date' => 'Date',
            'actions' => 'Actions',
            'appeal' => 'Recours',
            'pending' => 'En attente',
            'approved' => 'Approuvé',
            'rejected' => 'Rejeté',
            'cancelled' => 'Annulé',
            'view' => 'Voir',
            'cancel' => 'Annuler',
            'remind' => 'Rappeler',
            'login' => 'Connexion',
            'signup' => 'S\'inscrire',
            'logout' => 'Déconnexion',
            'account' => 'Compte',
            'english' => 'Anglais',
            'kinyarwanda' => 'Kinyarwanda',
            'french' => 'Français',
            'language' => 'Langue',
            'applications' => 'Demandes',
            'manage_account' => 'Gérer mon compte Irembo',
            'total_pending' => 'Total En attente',
            'position' => 'Position',
            'before_you' => 'Avant vous',
            
            // Services
            'replacement_of_national_id_card' => 'Remplacement de la CNI',
            'replacement_of_driving_license' => 'Remplacement du Permis',
            'replacement_of_passport' => 'Remplacement du Passeport',
            'marriage_certificate_cert' => 'Certificat de Mariage',
            'criminal_record_certificate' => 'Extrait de Casier Judiciaire',
            'certificate_of_good_conduct' => 'Certificat de Bonne Vie et Mœurs',
            'application_for_provisional_driving_license' => 'Permis de Conduire Provisoire',
            'application_for_definitive_driving_license' => 'Permis de Conduire Définitif',
            'application_for_new_passport' => 'Nouvelle Demande de Passeport'
        ]
    ];

    return $dictionary[$lang][$key] ?? $key;
}
?>
